### ISSUE TITLE
scraper - LUP, Coder, SSH not being scraped, i.e. missing episodes

### ISSUE THREAD

**Issue by gerbrent** [selfhostedshow/show-notes#29] opened 2024-03-25 20:33 UTC
LUP 553 onward are missing from notes.jupiterbroadcasting.com, 
Coder 561 onward aswell.

Likely due to the recent RSS changes?

https://notes.jupiterbroadcasting.com/linux-unplugged/
https://notes.jupiterbroadcasting.com/coder-radio/

**Comment by gerbrent** [comment] 2024-03-25 20:35
SSH > 118 also missing...

**Comment by RealOrangeOne** [comment] 2024-03-26 14:44
I think this is caused by https://github.com/selfhostedshow/show-notes/issues/23

**Comment by gerbrent** [comment] 2024-03-27 04:16
hmm, but https://selfhosted.show/json still seems fine and json as expected..

**Comment by ironicbadger** [comment] 2024-09-29 16:23
Fixed by #31

**Closed by ironicbadger** 2024-09-29 16:23 UTC
